### ISSUE TITLE
unrecognized symbols in several localetext.xx-XX.js files causes JavaScript errors

### ISSUE THREAD

**Issue by SiberianUser** [syncfusion/ej-global#41]
Hello, found out that there are several files in l10n folder have hidden unrecognized symbols (­­­­in some editors they look like double dash "--") and it causes runtime errors and therefore these localized texts does not apply to widgets:

ej.localetexts.fi-FI.js(600,76): 
ej.localetexts.fi-FI.js(935,76): 
ej.localetexts.fi-FI.js(1140,76):
ej.localetexts.pt-PT.js(605,50): 
ej.localetexts.pt-PT.js(936,70): 
ej.localetexts.pt-PT.js(940,50): 
ej.localetexts.pt-PT.js(1141,70):
ej.localetexts.pt-PT.js(1145,50):
ej.localetexts.ro-RO.js(599,69): 
ej.localetexts.ro-RO.js(934,69): 
ej.localetexts.ro-RO.js(1139,69):
ej.localetexts.ru-RU.js(598,61): 
ej.localetexts.ru-RU.js(933,61): 
ej.localetexts.ru-RU.js(1138,61):
ej.localetexts.sk-SK.js(600,69): 
ej.localetexts.sk-SK.js(936,69): 
ej.localetexts.sk-SK.js(1141,69):
ej.localetexts.tr-TR.js(603,43): 
ej.localetexts.tr-TR.js(935,57): 
ej.localetexts.tr-TR.js(939,43): 
ej.localetexts.tr-TR.js(1140,57):
ej.localetexts.tr-TR.js(1144,43):

**Comment by mohankumar91** [comment]
Hi SiberianUser,

Thanks for contacting Syncfusion support. 

Currently we are working on this reported issue and we will resolve it by September 19, 2017. 

Reagrds,
Mohankumar R

**Comment by mohankumar91** [comment]
Hi SiberianUser ,

Thanks for your patience. 

We would like to inform you that, we have fixed the reported issue and merged this fix in github.

Please let us know if you have any concerns. 

Regards,
Mohankumar R
